name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
          
      - name: Deploy to EC2 Server
        run: |
          rsync -avz --delete ./ ${{ secrets.EC2_USER }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            
            #Install Apache web server for launching the application
            sudo apt-get install -y apache2
            sudo systemctl daemon-reload
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            
            # Remove existing contents of /var/www/html
            sudo rm -rf /var/www/html/*
           
            # Move new files to /var/www/html
            sudo mv * /var/www/html
